require 'json'
require_relative 'vpcfrFormatter'

module VPCFR

  # A concrete class fulfilling the VPCFormatter template that
  # will produce a report in a Javascript Object Notation (JSON) format.
  #
  # @author Andy Akins
  # @since 1.0.0
  class VPCFRJSONFormatter
    include VPCFRFormatter

    # Take data created by a VPCFRParser and formats it into a string of
    # JSON records.
    #
    # @param [Hash,Array] data Data generated by VPCFRParser be be formatted into a report.
    # @return [String] String generated from provided data that has been formatted into a JSON report.
    def format(data)
      JSON.pretty_generate(data)
    end
  end
end
